ALTER TABLE "account_holders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "admin_audit_log" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "allocation_targets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "api_tokens" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "corporate_actions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dismissed_anomalies" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dividend_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fx_rates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ibkr_connections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "import_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "instruments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "last_prices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "loans" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "portfolio_intraday_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "portfolio_snapshots" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "portfolios" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "prices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "provider_credentials" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "provider_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "provider_usage" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scraped_quotes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "screenshot_imports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "storage_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tr_connections" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tr_resolved_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "transaction_sources" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "transactions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_preferences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "vision_provider_settings" ENABLE ROW LEVEL SECURITY;