import {
  pgTable,
  uuid,
  text,
  numeric,
  date,
  jsonb,
  timestamp,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { assetClassEnum, unitEnum } from "./enums.js";

export const instruments = pgTable(
  "instruments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    isin: text("isin").unique(),
    wkn: text("wkn").unique(),
    symbol: text("symbol").notNull(),
    market: text("market").notNull(),
    exchangeCode: text("exchange_code"),
    assetClass: assetClassEnum("asset_class").notNull(),
    unit: unitEnum("unit").notNull().default("shares"),
    currency: text("currency").notNull(),
    name: text("name").notNull(),
    displayName: text("display_name"),
    displayNameCheckedAt: timestamp("display_name_checked_at", { withTimezone: true }),
    sector: text("sector"),
    sectorWeights: jsonb("sector_weights").$type<Record<string, number>>(),
    sectorCheckedAt: timestamp("sector_checked_at", { withTimezone: true }),
    countryWeights: jsonb("country_weights").$type<Record<string, number>>(),
    countryCheckedAt: timestamp("country_checked_at", { withTimezone: true }),
    fundamentals: jsonb("fundamentals").$type<Record<string, unknown>>(),
    fundamentalsCheckedAt: timestamp("fundamentals_checked_at", { withTimezone: true }),
    faceValue: numeric("face_value"),
    couponRate: numeric("coupon_rate"),
    couponSchedule: text("coupon_schedule"),
    maturityDate: date("maturity_date"),
    partialExemptionRate: numeric("partial_exemption_rate"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("instruments_market_symbol_idx").on(t.market, t.symbol),
    index("instruments_symbol_trgm_idx").using("gin", t.symbol.op("gin_trgm_ops")),
    index("instruments_name_trgm_idx").using("gin", t.name.op("gin_trgm_ops")),
    index("instruments_isin_trgm_idx").using("gin", t.isin.op("gin_trgm_ops")),
    index("instruments_wkn_trgm_idx").using("gin", t.wkn.op("gin_trgm_ops")),
  ],
).enableRLS();
